creation_rules:
  - path_regex: secrets\.yaml$
    age:
      - age18z8qf8gnx4k7ewnm0x2z66sphgtau9grt8clsdz7usjyzk36w96qe6ny97
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE3YxxVgLik6ci8AD2hhEh832HD5y+3dPBUsd2vgJyad pscale01@gmail.com


